### ISSUE TITLE
Covariances

### ISSUE THREAD

**Issue by mintar** [paulbovbel/imu_rep_draft#4]
The proposed REP says:

> All message types provide a covariance matrix (see REP 103 [1]) alongside the data field (*_covariance). Unreported data dimensions should specify a diagonal covariance of -1.

This is a bit at odds with what [Imu.msg](https://github.com/ros/common_msgs/blob/d4b7d2bdc65c06d11d9e6a020d719874b5ce371a/sensor_msgs/msg/Imu.msg) says:

> If the covariance of the measurement is known, it should be filled in (if all you know is the 
> variance of each measurement, e.g. from the datasheet, just put those along the diagonal)
> A covariance matrix of all zeros will be interpreted as "covariance unknown", and to use the
> data a covariance will have to be assumed or gotten from some other source
> 
> If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation 
> estimate), please set element 0 of the associated covariance matrix to -1
> If you are interpreting this message, please check for a value of -1 in the first element of each 
> covariance matrix, and disregard the associated estimate.

So:

* Only the first element has to be set to -1, not the whole diagonal, and it signals that the whole field is invalid (e.g., `orientation`), not just one dimension of a field
* A covariance matrix of all zeros means "covariance unknown".

**Comment by paulbovbel** [comment]
Thanks, good catch.

**Comment by mintar** [comment]
Thanks!
